window.HCR_CASE_MODULES = window.HCR_CASE_MODULES || {};
window.HCR_CASE_MODULES.RC1 = window.HCR_CASE_MODULES.RC1 || {};

window.HCR_CASE_MODULES.RC1.module3 = {
    physicalExam: [
      { title:'Piel', helpId:'examen_piel', items:[{ id:'f01', source:'Examen físico', text:'Piel caliente y discretamente diaforética', termIds:['diaforesis','fiebre'] },{ id:'f02', source:'Examen físico', text:'Sin cianosis central ni petequias', termIds:['cianosis','petequias'] }] },
      { title:'Cabeza', helpId:'examen_cabeza', items:[{ id:'f03', source:'Examen físico', text:'Cabeza normocéfala, sin lesiones traumáticas' },{ id:'f04', source:'Examen físico', text:'Sin dolor a la palpación de senos frontales' }] },
      { title:'Ojos', helpId:'examen_ojos', items:[{ id:'f05', source:'Examen físico', text:'Conjuntivas rosadas, escleróticas anictéricas' },{ id:'f06', source:'Examen físico', text:'Pupilas isocóricas y reactivas' }] },
      { title:'Oídos', helpId:'examen_oidos', items:[{ id:'f07', source:'Examen físico', text:'Conductos auditivos sin secreción visible' },{ id:'f08', source:'Examen físico', text:'Audición conversacional conservada' }] },
      { title:'Nariz y senos paranasales', helpId:'examen_nariz_senos', items:[{ id:'f09', source:'Examen físico', text:'Mucosa nasal levemente congestiva, sin secreción purulenta' },{ id:'f10', source:'Examen físico', text:'Senos paranasales no dolorosos a la palpación' }] },
      { title:'Boca', helpId:'examen_boca_faringe', items:[{ id:'f11', source:'Examen físico', text:'Mucosa oral ligeramente seca' },{ id:'f12', source:'Examen físico', text:'Dentición con caries antiguas, sin absceso visible' }] },
      { title:'Faringe', helpId:'examen_boca_faringe', items:[{ id:'f13', source:'Examen físico', text:'Faringe sin exudado ni placas' },{ id:'f14', source:'Examen físico', text:'Leve eritema faríngeo inespecífico' }] },
      { title:'Cuello', helpId:'examen_cuello', items:[{ id:'f15', source:'Examen físico', text:'Cuello móvil, sin rigidez de nuca' },{ id:'f16', source:'Examen físico', text:'No ingurgitación yugular a 45 grados', termIds:['ingurgitacion_yugular'] }] },
      { title:'Ganglios linfáticos', helpId:'examen_ganglios_linfaticos', items:[{ id:'f17', source:'Examen físico', text:'Sin adenopatías cervicales o supraclaviculares palpables' },{ id:'f18', source:'Examen físico', text:'Sin adenopatías dolorosas en cadenas axilares' }] },
      { title:'Tórax', helpId:'examen_torax', items:[{ id:'f19', source:'Examen físico', text:'Expansión torácica disminuida en base derecha' },{ id:'f20', source:'Examen físico', text:'Dolor leve a la inspiración profunda, sin dolor a la palpación de pared torácica', termIds:['dolor_pleuritico'] }] },
      { title:'Senos', helpId:'examen_senos', items:[{ id:'f21', source:'Examen físico', text:'Sin hallazgos mamarios de alarma a la inspección rápida' },{ id:'f22', source:'Examen físico', text:'Sin secreción por pezones' }] },
      { title:'Pulmones', helpId:'examen_respiratorio', items:[{ id:'f23', source:'Examen físico', text:'Matidez a la percusión en base pulmonar derecha', termIds:['matidez_percusion'] },{ id:'f24', source:'Examen físico', text:'Estertores crepitantes localizados en base derecha', termIds:['estertores'] },{ id:'f25', source:'Examen físico', text:'Soplo tubario en campo basal derecho' },{ id:'f26', source:'Examen físico', text:'Egofonía positiva en base derecha', termIds:['egofonia'] },{ id:'f27', source:'Examen físico', text:'Sin sibilancias difusas', termIds:['sibilancias'] },{ id:'f28', source:'Examen físico', text:'Murmullo vesicular conservado en hemitórax izquierdo', termIds:['murmullo_vesicular'] }] },
      { title:'Corazón', helpId:'examen_cardiovascular', items:[{ id:'f29', source:'Examen físico', text:'Ritmo regular, taquicárdico', termIds:['taquicardia'] },{ id:'f30', source:'Examen físico', text:'Ruidos cardíacos audibles, sin soplos nuevos', termIds:['soplo_cardiaco'] },{ id:'f31', source:'Examen físico', text:'Sin roce pericárdico', termIds:['roce_pericardico'] }] },
      { title:'Vasos sanguíneos', helpId:'examen_cardiovascular', items:[{ id:'f32', source:'Examen físico', text:'Pulsos periféricos palpables y simétricos', termIds:['pulsos_perifericos'] },{ id:'f33', source:'Examen físico', text:'Llenado capilar menor de 2 segundos', termIds:['llenado_capilar'] }] },
      { title:'Abdomen', helpId:'examen_abdominal', items:[{ id:'f34', source:'Examen físico', text:'Abdomen blando, depresible, no doloroso' },{ id:'f35', source:'Examen físico', text:'Ruidos hidroaéreos presentes' },{ id:'f36', source:'Examen físico', text:'Sin visceromegalias palpables' }] },
      { title:'Genitales masculinos', helpId:'examen_genitourinario', items:[{ id:'f37', source:'Examen físico', text:'Examen genital no prioritario; niega síntomas genitourinarios agudos' },{ id:'f38', source:'Examen físico', text:'Sin lesiones genitales referidas' }] },
      { title:'Recto', helpId:'examen_rectal', items:[{ id:'f39', source:'Examen físico', text:'Examen rectal diferido por ausencia de indicación inmediata' },{ id:'f40', source:'Examen físico', text:'Niega sangrado rectal o dolor anal' }] },
      { title:'Huesos, articulaciones y músculos', helpId:'examen_osteomuscular', items:[{ id:'f41', source:'Examen físico', text:'Sin artritis aguda ni deformidad articular nueva' },{ id:'f42', source:'Examen físico', text:'Dolor muscular difuso leve durante picos febriles', termIds:['fiebre'] }] },
      { title:'Extremidades', helpId:'examen_extremidades_perifericas', items:[{ id:'f43', source:'Examen físico', text:'Sin edema periférico', termIds:['edema_periferico'] },{ id:'f44', source:'Examen físico', text:'Sin dolor a la palpación de pantorrillas' },{ id:'f45', source:'Examen físico', text:'Extremidades tibias y simétricas' }] },
      { title:'Neurológico y psíquico', helpId:'examen_neurologico', items:[{ id:'f46', source:'Examen físico', text:'Paciente vigil y orientado en persona, tiempo y espacio' },{ id:'f47', source:'Examen físico', text:'Lenguaje fluido, sin déficit focal evidente', termIds:['deficit_neurologico_focal'] },{ id:'f48', source:'Examen físico', text:'Sin signos meníngeos' }] }
    ]
  };
